# Generated by Django 3.2.7 on 2022-02-16 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_loginpage_registerpage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LoginPage',
        ),
        migrations.DeleteModel(
            name='RegisterPage',
        ),
    ]
